/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nLX.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;
import org.xixum.modeler.spelling.nLX.BlockElement;
import org.xixum.modeler.spelling.nLX.NLXPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Block Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BlockElementImpl extends MinimalEObjectImpl.Container implements BlockElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BlockElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NLXPackage.Literals.BLOCK_ELEMENT;
  }

} //BlockElementImpl
