/**
 * generated by Xtext 2.36.0
 */
package org.xixum.modeler.spelling.nlx.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xixum.modeler.spelling.nlx.FreeSentence;
import org.xixum.modeler.spelling.nlx.NlxPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Free Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FreeSentenceImpl extends MinimalEObjectImpl.Container implements FreeSentence
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FreeSentenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NlxPackage.Literals.FREE_SENTENCE;
  }

} //FreeSentenceImpl
