/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nlx.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xixum.modeler.spelling.nlx.FreeSubSentence;
import org.xixum.modeler.spelling.nlx.Nlx2Package;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Free Sub Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FreeSubSentenceImpl extends MinimalEObjectImpl.Container implements FreeSubSentence
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FreeSubSentenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Nlx2Package.Literals.FREE_SUB_SENTENCE;
  }

} //FreeSubSentenceImpl
