/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nlx.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xixum.modeler.spelling.nlx.LineSubSentence;
import org.xixum.modeler.spelling.nlx.NlxPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Line Sub Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class LineSubSentenceImpl extends MinimalEObjectImpl.Container implements LineSubSentence
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LineSubSentenceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NlxPackage.Literals.LINE_SUB_SENTENCE;
  }

} //LineSubSentenceImpl
