/**
 * generated by Xtext 2.36.0
 */
package org.xixum.modeler.spelling.nlx.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xixum.modeler.spelling.nlx.NlxPackage;
import org.xixum.modeler.spelling.nlx.SentenceChainX;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Sentence Chain X</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SentenceChainXImpl extends MinimalEObjectImpl.Container implements SentenceChainX
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SentenceChainXImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NlxPackage.Literals.SENTENCE_CHAIN_X;
  }

} //SentenceChainXImpl
