/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nLX.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;
import org.xixum.modeler.spelling.nLX.NLXPackage;
import org.xixum.modeler.spelling.nLX.TableBorder;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Table Border</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TableBorderImpl extends MinimalEObjectImpl.Container implements TableBorder
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TableBorderImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NLXPackage.Literals.TABLE_BORDER;
  }

} //TableBorderImpl
