/*
 * generated by template
 */
package org.xixum.modeler.docgen.template.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xixum.modeler.docgen.template.ui.internal.TemplateActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TemplateExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TemplateActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TemplateActivator activator = TemplateActivator.getInstance();
		return activator != null ? activator.getInjector(TemplateActivator.ORG_XIXUM_MODELER_DOCGEN_TEMPLATE_TEMPLATE) : null;
	}

}
