/*
 * generated by Xtext 2.33.0
 */
package org.xixum.latex.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTexDslScopeProvider extends DelegatingScopeProvider {
}
