/*
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling;

import org.xixum.modeler.spelling.NLXStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class NLXStandaloneSetup extends NLXStandaloneSetupGenerated {

	public static void doSetup() {
		new NLXStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
