/*
 * generated by Xtext 2.33.0
 */
package org.xixum.latex.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TexDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xixum/latex/parser/antlr/internal/InternalTexDsl.tokens");
	}
}
