/**
 * generated by template
 */
package org.xixum.modeler.docgen.template.template.provider;


import java.util.Collection;
import java.util.List;

import org.eclipse.emf.common.notify.AdapterFactory;
import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.common.util.ResourceLocator;

import org.eclipse.emf.ecore.EStructuralFeature;

import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.IItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ItemPropertyDescriptor;
import org.eclipse.emf.edit.provider.ItemProviderAdapter;
import org.eclipse.emf.edit.provider.ViewerNotification;

import org.eclipse.xtext.xbase.XbaseFactory;
import org.eclipse.xtext.xbase.XbasePackage;

import org.eclipse.xtext.xbase.annotations.xAnnotations.XAnnotationsFactory;
import org.xixum.modeler.docgen.template.template.RichStringIf;
import org.xixum.modeler.docgen.template.template.TemplateFactory;
import org.xixum.modeler.docgen.template.template.TemplatePackage;

/**
 * This is the item provider adapter for a {@link org.xixum.modeler.docgen.template.template.RichStringIf} object.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class RichStringIfItemProvider extends ItemProviderAdapter {
	/**
	 * This constructs an instance from a factory and a notifier.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RichStringIfItemProvider(AdapterFactory adapterFactory) {
		super(adapterFactory);
	}

	/**
	 * This returns the property descriptors for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public List<IItemPropertyDescriptor> getPropertyDescriptors(Object object) {
		if (itemPropertyDescriptors == null) {
			super.getPropertyDescriptors(object);

			addConditionalExpressionPropertyDescriptor(object);
		}
		return itemPropertyDescriptors;
	}

	/**
	 * This adds a property descriptor for the Conditional Expression feature.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @since 2.18
	 * @generated
	 */
	protected void addConditionalExpressionPropertyDescriptor(Object object) {
		itemPropertyDescriptors.add
			(createItemPropertyDescriptor
				(((ComposeableAdapterFactory)adapterFactory).getRootAdapterFactory(),
				 getResourceLocator(),
				 getString("_UI_XIfExpression_conditionalExpression_feature"),
				 getString("_UI_PropertyDescriptor_description", "_UI_XIfExpression_conditionalExpression_feature", "_UI_XIfExpression_type"),
				 XbasePackage.Literals.XIF_EXPRESSION__CONDITIONAL_EXPRESSION,
				 true,
				 false,
				 false,
				 ItemPropertyDescriptor.BOOLEAN_VALUE_IMAGE,
				 null,
				 null));
	}

	/**
	 * This specifies how to implement {@link #getChildren} and is used to deduce an appropriate feature for an
	 * {@link org.eclipse.emf.edit.command.AddCommand}, {@link org.eclipse.emf.edit.command.RemoveCommand} or
	 * {@link org.eclipse.emf.edit.command.MoveCommand} in {@link #createCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Collection<? extends EStructuralFeature> getChildrenFeatures(Object object) {
		if (childrenFeatures == null) {
			super.getChildrenFeatures(object);
			childrenFeatures.add(XbasePackage.Literals.XIF_EXPRESSION__IF);
			childrenFeatures.add(XbasePackage.Literals.XIF_EXPRESSION__THEN);
			childrenFeatures.add(XbasePackage.Literals.XIF_EXPRESSION__ELSE);
		}
		return childrenFeatures;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EStructuralFeature getChildFeature(Object object, Object child) {
		// Check the type of the specified child object and return the proper feature to use for
		// adding (see {@link AddCommand}) it as a child.

		return super.getChildFeature(object, child);
	}

	/**
	 * This returns RichStringIf.gif.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object getImage(Object object) {
		return overlayImage(object, getResourceLocator().getImage("full/obj16/RichStringIf"));
	}

	/**
	 * This returns the label text for the adapted class.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getText(Object object) {
		RichStringIf richStringIf = (RichStringIf)object;
		return getString("_UI_RichStringIf_type") + " " + richStringIf.isConditionalExpression();
	}


	/**
	 * This handles model notifications by calling {@link #updateChildren} to update any cached
	 * children and by creating a viewer notification, which it passes to {@link #fireNotifyChanged}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void notifyChanged(Notification notification) {
		updateChildren(notification);

		switch (notification.getFeatureID(RichStringIf.class)) {
			case TemplatePackage.RICH_STRING_IF__CONDITIONAL_EXPRESSION:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), false, true));
				return;
			case TemplatePackage.RICH_STRING_IF__IF:
			case TemplatePackage.RICH_STRING_IF__THEN:
			case TemplatePackage.RICH_STRING_IF__ELSE:
				fireNotifyChanged(new ViewerNotification(notification, notification.getNotifier(), true, false));
				return;
		}
		super.notifyChanged(notification);
	}

	/**
	 * This adds {@link org.eclipse.emf.edit.command.CommandParameter}s describing the children
	 * that can be created under this object.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected void collectNewChildDescriptors(Collection<Object> newChildDescriptors, Object object) {
		super.collectNewChildDescriptors(newChildDescriptors, object);

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 TemplateFactory.eINSTANCE.createRichString()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 TemplateFactory.eINSTANCE.createRichStringLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 TemplateFactory.eINSTANCE.createRichStringForLoop()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 TemplateFactory.eINSTANCE.createRichStringIf()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XAnnotationsFactory.eINSTANCE.createXAnnotation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXIfExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXSwitchExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXBlockExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXVariableDeclaration()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXMemberFeatureCall()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXFeatureCall()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXConstructorCall()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXBooleanLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXNullLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXNumberLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXStringLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXListLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXSetLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXClosure()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXCastedExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXBinaryOperation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXUnaryOperation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXPostfixOperation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXForLoopExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXBasicForLoopExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXDoWhileExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXWhileExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXTypeLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXInstanceOfExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXThrowExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXTryCatchFinallyExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXAssignment()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXReturnExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__IF,
				 XbaseFactory.eINSTANCE.createXSynchronizedExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 TemplateFactory.eINSTANCE.createRichString()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 TemplateFactory.eINSTANCE.createRichStringLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 TemplateFactory.eINSTANCE.createRichStringForLoop()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 TemplateFactory.eINSTANCE.createRichStringIf()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XAnnotationsFactory.eINSTANCE.createXAnnotation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXIfExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXSwitchExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXBlockExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXVariableDeclaration()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXMemberFeatureCall()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXFeatureCall()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXConstructorCall()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXBooleanLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXNullLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXNumberLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXStringLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXListLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXSetLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXClosure()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXCastedExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXBinaryOperation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXUnaryOperation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXPostfixOperation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXForLoopExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXBasicForLoopExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXDoWhileExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXWhileExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXTypeLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXInstanceOfExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXThrowExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXTryCatchFinallyExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXAssignment()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXReturnExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__THEN,
				 XbaseFactory.eINSTANCE.createXSynchronizedExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 TemplateFactory.eINSTANCE.createRichString()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 TemplateFactory.eINSTANCE.createRichStringLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 TemplateFactory.eINSTANCE.createRichStringForLoop()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 TemplateFactory.eINSTANCE.createRichStringIf()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XAnnotationsFactory.eINSTANCE.createXAnnotation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXIfExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXSwitchExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXBlockExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXVariableDeclaration()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXMemberFeatureCall()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXFeatureCall()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXConstructorCall()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXBooleanLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXNullLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXNumberLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXStringLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXListLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXSetLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXClosure()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXCastedExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXBinaryOperation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXUnaryOperation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXPostfixOperation()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXForLoopExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXBasicForLoopExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXDoWhileExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXWhileExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXTypeLiteral()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXInstanceOfExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXThrowExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXTryCatchFinallyExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXAssignment()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXReturnExpression()));

		newChildDescriptors.add
			(createChildParameter
				(XbasePackage.Literals.XIF_EXPRESSION__ELSE,
				 XbaseFactory.eINSTANCE.createXSynchronizedExpression()));
	}

	/**
	 * This returns the label text for {@link org.eclipse.emf.edit.command.CreateChildCommand}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public String getCreateChildText(Object owner, Object feature, Object child, Collection<?> selection) {
		Object childFeature = feature;
		Object childObject = child;

		boolean qualify =
			childFeature == XbasePackage.Literals.XIF_EXPRESSION__IF ||
			childFeature == XbasePackage.Literals.XIF_EXPRESSION__THEN ||
			childFeature == XbasePackage.Literals.XIF_EXPRESSION__ELSE;

		if (qualify) {
			return getString
				("_UI_CreateChild_text2",
				 new Object[] { getTypeText(childObject), getFeatureText(childFeature), getTypeText(owner) });
		}
		return super.getCreateChildText(owner, feature, child, selection);
	}

	/**
	 * Return the resource locator for this item provider's resources.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ResourceLocator getResourceLocator() {
		return TemplateEditPlugin.INSTANCE;
	}

}
