/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nLX;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chapter Unit HI</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.modeler.spelling.nLX.NLXPackage#getChapter_Unit_HI()
 * @model
 * @generated
 */
public interface Chapter_Unit_HI extends EObject
{
} // Chapter_Unit_HI
