/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nlx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ext Bracket Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.modeler.spelling.nlx.Nlx2Package#getExtBracketSentence()
 * @model
 * @generated
 */
public interface ExtBracketSentence extends BracketSentence
{
} // ExtBracketSentence
