/**
 * generated by Xtext 2.36.0
 */
package org.xixum.modeler.spelling.nlx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Foot Note</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.modeler.spelling.nlx.FootNote#getNumber <em>Number</em>}</li>
 *   <li>{@link org.xixum.modeler.spelling.nlx.FootNote#getSentenceChain <em>Sentence Chain</em>}</li>
 * </ul>
 *
 * @see org.xixum.modeler.spelling.nlx.NlxPackage#getFootNote()
 * @model
 * @generated
 */
public interface FootNote extends BlockElement
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(String)
   * @see org.xixum.modeler.spelling.nlx.NlxPackage#getFootNote_Number()
   * @model
   * @generated
   */
  String getNumber();

  /**
   * Sets the value of the '{@link org.xixum.modeler.spelling.nlx.FootNote#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(String value);

  /**
   * Returns the value of the '<em><b>Sentence Chain</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sentence Chain</em>' containment reference.
   * @see #setSentenceChain(SentenceChain)
   * @see org.xixum.modeler.spelling.nlx.NlxPackage#getFootNote_SentenceChain()
   * @model containment="true"
   * @generated
   */
  SentenceChain getSentenceChain();

  /**
   * Sets the value of the '{@link org.xixum.modeler.spelling.nlx.FootNote#getSentenceChain <em>Sentence Chain</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sentence Chain</em>' containment reference.
   * @see #getSentenceChain()
   * @generated
   */
  void setSentenceChain(SentenceChain value);

} // FootNote
