/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nLX;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hash Number</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.modeler.spelling.nLX.NLXPackage#getHashNumber()
 * @model
 * @generated
 */
public interface HashNumber extends NoNElement
{
} // HashNumber
