/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nLX;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Line Sub Sentence</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.modeler.spelling.nLX.NLXPackage#getLineSubSentence()
 * @model
 * @generated
 */
public interface LineSubSentence extends EObject
{
} // LineSubSentence
