/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nlx;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>No NElement X2</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.modeler.spelling.nlx.Nlx2Package#getNoNElementX2()
 * @model
 * @generated
 */
public interface NoNElementX2 extends Elements
{
} // NoNElementX2
