/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nLX;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Paragraph Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.modeler.spelling.nLX.ParagraphBlock#getBlock <em>Block</em>}</li>
 * </ul>
 *
 * @see org.xixum.modeler.spelling.nLX.NLXPackage#getParagraphBlock()
 * @model
 * @generated
 */
public interface ParagraphBlock extends SentenceType
{
  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference list.
   * The list contents are of type {@link org.xixum.modeler.spelling.nLX.BlockElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference list.
   * @see org.xixum.modeler.spelling.nLX.NLXPackage#getParagraphBlock_Block()
   * @model containment="true"
   * @generated
   */
  EList<BlockElement> getBlock();

} // ParagraphBlock
