/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nLX;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Url Adress</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.modeler.spelling.nLX.UrlAdress#getProtocol <em>Protocol</em>}</li>
 *   <li>{@link org.xixum.modeler.spelling.nLX.UrlAdress#getUrl <em>Url</em>}</li>
 * </ul>
 *
 * @see org.xixum.modeler.spelling.nLX.NLXPackage#getUrlAdress()
 * @model
 * @generated
 */
public interface UrlAdress extends NoNElement
{
  /**
   * Returns the value of the '<em><b>Protocol</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Protocol</em>' attribute.
   * @see #setProtocol(String)
   * @see org.xixum.modeler.spelling.nLX.NLXPackage#getUrlAdress_Protocol()
   * @model
   * @generated
   */
  String getProtocol();

  /**
   * Sets the value of the '{@link org.xixum.modeler.spelling.nLX.UrlAdress#getProtocol <em>Protocol</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Protocol</em>' attribute.
   * @see #getProtocol()
   * @generated
   */
  void setProtocol(String value);

  /**
   * Returns the value of the '<em><b>Url</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Url</em>' attribute list.
   * @see org.xixum.modeler.spelling.nLX.NLXPackage#getUrlAdress_Url()
   * @model unique="false"
   * @generated
   */
  EList<String> getUrl();

} // UrlAdress
