/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nlx2.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xixum.modeler.spelling.nlx.NlxPackage;
import org.xixum.modeler.spelling.nlx.NoNElementX;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>No NElement X</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class NoNElementXImpl extends MinimalEObjectImpl.Container implements NoNElementX
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NoNElementXImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NlxPackage.Literals.NO_NELEMENT_X;
  }

} //NoNElementXImpl
