/**
 * generated by Xtext 2.33.0
 */
package org.xixum.latex.texDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.latex.texDsl.Command#getCommand <em>Command</em>}</li>
 *   <li>{@link org.xixum.latex.texDsl.Command#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.xixum.latex.texDsl.Command#getSubCommand <em>Sub Command</em>}</li>
 * </ul>
 *
 * @see org.xixum.latex.texDsl.TexDslPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends EObject
{
  /**
   * Returns the value of the '<em><b>Command</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' containment reference.
   * @see #setCommand(CommandName)
   * @see org.xixum.latex.texDsl.TexDslPackage#getCommand_Command()
   * @model containment="true"
   * @generated
   */
  CommandName getCommand();

  /**
   * Sets the value of the '{@link org.xixum.latex.texDsl.Command#getCommand <em>Command</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' containment reference.
   * @see #getCommand()
   * @generated
   */
  void setCommand(CommandName value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference.
   * @see #setParameters(CommandParameters)
   * @see org.xixum.latex.texDsl.TexDslPackage#getCommand_Parameters()
   * @model containment="true"
   * @generated
   */
  CommandParameters getParameters();

  /**
   * Sets the value of the '{@link org.xixum.latex.texDsl.Command#getParameters <em>Parameters</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parameters</em>' containment reference.
   * @see #getParameters()
   * @generated
   */
  void setParameters(CommandParameters value);

  /**
   * Returns the value of the '<em><b>Sub Command</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub Command</em>' containment reference.
   * @see #setSubCommand(SubCommand)
   * @see org.xixum.latex.texDsl.TexDslPackage#getCommand_SubCommand()
   * @model containment="true"
   * @generated
   */
  SubCommand getSubCommand();

  /**
   * Sets the value of the '{@link org.xixum.latex.texDsl.Command#getSubCommand <em>Sub Command</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub Command</em>' containment reference.
   * @see #getSubCommand()
   * @generated
   */
  void setSubCommand(SubCommand value);

} // Command
