/**
 * generated by Xtext 2.33.0
 */
package org.xixum.latex.texDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.latex.texDsl.Command#getCommand <em>Command</em>}</li>
 *   <li>{@link org.xixum.latex.texDsl.Command#getAttrs <em>Attrs</em>}</li>
 *   <li>{@link org.xixum.latex.texDsl.Command#getTokens <em>Tokens</em>}</li>
 * </ul>
 *
 * @see org.xixum.latex.texDsl.TexDslPackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends Document
{
  /**
   * Returns the value of the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' attribute.
   * @see #setCommand(String)
   * @see org.xixum.latex.texDsl.TexDslPackage#getCommand_Command()
   * @model
   * @generated
   */
  String getCommand();

  /**
   * Sets the value of the '{@link org.xixum.latex.texDsl.Command#getCommand <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' attribute.
   * @see #getCommand()
   * @generated
   */
  void setCommand(String value);

  /**
   * Returns the value of the '<em><b>Attrs</b></em>' containment reference list.
   * The list contents are of type {@link org.xixum.latex.texDsl.Attributes}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attrs</em>' containment reference list.
   * @see org.xixum.latex.texDsl.TexDslPackage#getCommand_Attrs()
   * @model containment="true"
   * @generated
   */
  EList<Attributes> getAttrs();

  /**
   * Returns the value of the '<em><b>Tokens</b></em>' containment reference list.
   * The list contents are of type {@link org.xixum.latex.texDsl.Compound}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tokens</em>' containment reference list.
   * @see org.xixum.latex.texDsl.TexDslPackage#getCommand_Tokens()
   * @model containment="true"
   * @generated
   */
  EList<Compound> getTokens();

} // Command
