/**
 * generated by Xtext 2.33.0
 */
package org.xixum.latex.texDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.latex.texDsl.TexDslPackage#getDocument()
 * @model
 * @generated
 */
public interface Document extends EObject
{
} // Document
