/**
 * generated by Xtext 2.33.0
 */
package org.xixum.latex.texDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Document</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.latex.texDsl.Document#getElements <em>Elements</em>}</li>
 * </ul>
 *
 * @see org.xixum.latex.texDsl.TexDslPackage#getDocument()
 * @model
 * @generated
 */
public interface Document extends EObject
{
  /**
   * Returns the value of the '<em><b>Elements</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Elements</em>' containment reference list.
   * @see org.xixum.latex.texDsl.TexDslPackage#getDocument_Elements()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getElements();

} // Document
