/**
 * generated by Xtext 2.33.0
 */
package org.xixum.latex.texDsl;

import java.math.BigDecimal;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Numbers</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.latex.texDsl.Numbers#getNum <em>Num</em>}</li>
 * </ul>
 *
 * @see org.xixum.latex.texDsl.TexDslPackage#getNumbers()
 * @model
 * @generated
 */
public interface Numbers extends TextContent
{
  /**
   * Returns the value of the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Num</em>' attribute.
   * @see #setNum(BigDecimal)
   * @see org.xixum.latex.texDsl.TexDslPackage#getNumbers_Num()
   * @model
   * @generated
   */
  BigDecimal getNum();

  /**
   * Sets the value of the '{@link org.xixum.latex.texDsl.Numbers#getNum <em>Num</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Num</em>' attribute.
   * @see #getNum()
   * @generated
   */
  void setNum(BigDecimal value);

} // Numbers
