/**
 * generated by Xtext 2.33.0
 */
package org.xixum.latex.texDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.latex.texDsl.Text#getToken <em>Token</em>}</li>
 * </ul>
 *
 * @see org.xixum.latex.texDsl.TexDslPackage#getText()
 * @model
 * @generated
 */
public interface Text extends Document
{
  /**
   * Returns the value of the '<em><b>Token</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Token</em>' attribute list.
   * @see org.xixum.latex.texDsl.TexDslPackage#getText_Token()
   * @model unique="false"
   * @generated
   */
  EList<String> getToken();

} // Text
