/**
 * generated by Xtext 2.33.0
 */
package org.xixum.latex.texDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xixum.latex.texDsl.TexDslFactory
 * @model kind="package"
 * @generated
 */
public interface TexDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "texDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xixum.org/latex/TexDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "texDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TexDslPackage eINSTANCE = org.xixum.latex.texDsl.impl.TexDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xixum.latex.texDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xixum.latex.texDsl.impl.ModelImpl
   * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Document</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__DOCUMENT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xixum.latex.texDsl.impl.DocumentImpl <em>Document</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xixum.latex.texDsl.impl.DocumentImpl
   * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getDocument()
   * @generated
   */
  int DOCUMENT = 1;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Document</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOCUMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xixum.latex.texDsl.impl.TokenImpl <em>Token</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xixum.latex.texDsl.impl.TokenImpl
   * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getToken()
   * @generated
   */
  int TOKEN = 2;

  /**
   * The feature id for the '<em><b>Token</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOKEN__TOKEN = 0;

  /**
   * The number of structural features of the '<em>Token</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOKEN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xixum.latex.texDsl.impl.CommandNameImpl <em>Command Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xixum.latex.texDsl.impl.CommandNameImpl
   * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getCommandName()
   * @generated
   */
  int COMMAND_NAME = 3;

  /**
   * The feature id for the '<em><b>Leading</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_NAME__LEADING = 0;

  /**
   * The feature id for the '<em><b>CName</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_NAME__CNAME = 1;

  /**
   * The number of structural features of the '<em>Command Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_NAME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xixum.latex.texDsl.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xixum.latex.texDsl.impl.CommandImpl
   * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 4;

  /**
   * The feature id for the '<em><b>Command</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__COMMAND = 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__ATTRIBUTES = 1;

  /**
   * The feature id for the '<em><b>Types</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__TYPES = 2;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xixum.latex.texDsl.impl.AttributesImpl <em>Attributes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xixum.latex.texDsl.impl.AttributesImpl
   * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getAttributes()
   * @generated
   */
  int ATTRIBUTES = 5;

  /**
   * The feature id for the '<em><b>Key</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTES__KEY = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTES__VALUE = 1;

  /**
   * The feature id for the '<em><b>Multi Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTES__MULTI_VALUE = 2;

  /**
   * The number of structural features of the '<em>Attributes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTES_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xixum.latex.texDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xixum.latex.texDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xixum.latex.texDsl.Model#getDocument <em>Document</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Document</em>'.
   * @see org.xixum.latex.texDsl.Model#getDocument()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Document();

  /**
   * Returns the meta object for class '{@link org.xixum.latex.texDsl.Document <em>Document</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Document</em>'.
   * @see org.xixum.latex.texDsl.Document
   * @generated
   */
  EClass getDocument();

  /**
   * Returns the meta object for the containment reference list '{@link org.xixum.latex.texDsl.Document#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xixum.latex.texDsl.Document#getElements()
   * @see #getDocument()
   * @generated
   */
  EReference getDocument_Elements();

  /**
   * Returns the meta object for class '{@link org.xixum.latex.texDsl.Token <em>Token</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Token</em>'.
   * @see org.xixum.latex.texDsl.Token
   * @generated
   */
  EClass getToken();

  /**
   * Returns the meta object for the attribute '{@link org.xixum.latex.texDsl.Token#getToken <em>Token</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Token</em>'.
   * @see org.xixum.latex.texDsl.Token#getToken()
   * @see #getToken()
   * @generated
   */
  EAttribute getToken_Token();

  /**
   * Returns the meta object for class '{@link org.xixum.latex.texDsl.CommandName <em>Command Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Name</em>'.
   * @see org.xixum.latex.texDsl.CommandName
   * @generated
   */
  EClass getCommandName();

  /**
   * Returns the meta object for the attribute '{@link org.xixum.latex.texDsl.CommandName#getLeading <em>Leading</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Leading</em>'.
   * @see org.xixum.latex.texDsl.CommandName#getLeading()
   * @see #getCommandName()
   * @generated
   */
  EAttribute getCommandName_Leading();

  /**
   * Returns the meta object for the attribute list '{@link org.xixum.latex.texDsl.CommandName#getCName <em>CName</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>CName</em>'.
   * @see org.xixum.latex.texDsl.CommandName#getCName()
   * @see #getCommandName()
   * @generated
   */
  EAttribute getCommandName_CName();

  /**
   * Returns the meta object for class '{@link org.xixum.latex.texDsl.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xixum.latex.texDsl.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the containment reference '{@link org.xixum.latex.texDsl.Command#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Command</em>'.
   * @see org.xixum.latex.texDsl.Command#getCommand()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Command();

  /**
   * Returns the meta object for the containment reference list '{@link org.xixum.latex.texDsl.Command#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.xixum.latex.texDsl.Command#getAttributes()
   * @see #getCommand()
   * @generated
   */
  EReference getCommand_Attributes();

  /**
   * Returns the meta object for the attribute list '{@link org.xixum.latex.texDsl.Command#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Types</em>'.
   * @see org.xixum.latex.texDsl.Command#getTypes()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Types();

  /**
   * Returns the meta object for class '{@link org.xixum.latex.texDsl.Attributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attributes</em>'.
   * @see org.xixum.latex.texDsl.Attributes
   * @generated
   */
  EClass getAttributes();

  /**
   * Returns the meta object for the containment reference '{@link org.xixum.latex.texDsl.Attributes#getKey <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Key</em>'.
   * @see org.xixum.latex.texDsl.Attributes#getKey()
   * @see #getAttributes()
   * @generated
   */
  EReference getAttributes_Key();

  /**
   * Returns the meta object for the attribute '{@link org.xixum.latex.texDsl.Attributes#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xixum.latex.texDsl.Attributes#getValue()
   * @see #getAttributes()
   * @generated
   */
  EAttribute getAttributes_Value();

  /**
   * Returns the meta object for the attribute list '{@link org.xixum.latex.texDsl.Attributes#getMultiValue <em>Multi Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Multi Value</em>'.
   * @see org.xixum.latex.texDsl.Attributes#getMultiValue()
   * @see #getAttributes()
   * @generated
   */
  EAttribute getAttributes_MultiValue();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TexDslFactory getTexDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xixum.latex.texDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xixum.latex.texDsl.impl.ModelImpl
     * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Document</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__DOCUMENT = eINSTANCE.getModel_Document();

    /**
     * The meta object literal for the '{@link org.xixum.latex.texDsl.impl.DocumentImpl <em>Document</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xixum.latex.texDsl.impl.DocumentImpl
     * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getDocument()
     * @generated
     */
    EClass DOCUMENT = eINSTANCE.getDocument();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOCUMENT__ELEMENTS = eINSTANCE.getDocument_Elements();

    /**
     * The meta object literal for the '{@link org.xixum.latex.texDsl.impl.TokenImpl <em>Token</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xixum.latex.texDsl.impl.TokenImpl
     * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getToken()
     * @generated
     */
    EClass TOKEN = eINSTANCE.getToken();

    /**
     * The meta object literal for the '<em><b>Token</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOKEN__TOKEN = eINSTANCE.getToken_Token();

    /**
     * The meta object literal for the '{@link org.xixum.latex.texDsl.impl.CommandNameImpl <em>Command Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xixum.latex.texDsl.impl.CommandNameImpl
     * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getCommandName()
     * @generated
     */
    EClass COMMAND_NAME = eINSTANCE.getCommandName();

    /**
     * The meta object literal for the '<em><b>Leading</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND_NAME__LEADING = eINSTANCE.getCommandName_Leading();

    /**
     * The meta object literal for the '<em><b>CName</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND_NAME__CNAME = eINSTANCE.getCommandName_CName();

    /**
     * The meta object literal for the '{@link org.xixum.latex.texDsl.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xixum.latex.texDsl.impl.CommandImpl
     * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__COMMAND = eINSTANCE.getCommand_Command();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMMAND__ATTRIBUTES = eINSTANCE.getCommand_Attributes();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__TYPES = eINSTANCE.getCommand_Types();

    /**
     * The meta object literal for the '{@link org.xixum.latex.texDsl.impl.AttributesImpl <em>Attributes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xixum.latex.texDsl.impl.AttributesImpl
     * @see org.xixum.latex.texDsl.impl.TexDslPackageImpl#getAttributes()
     * @generated
     */
    EClass ATTRIBUTES = eINSTANCE.getAttributes();

    /**
     * The meta object literal for the '<em><b>Key</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTES__KEY = eINSTANCE.getAttributes_Key();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTES__VALUE = eINSTANCE.getAttributes_Value();

    /**
     * The meta object literal for the '<em><b>Multi Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTES__MULTI_VALUE = eINSTANCE.getAttributes_MultiValue();

  }

} //TexDslPackage
