/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nlx2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Brackets</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xixum.modeler.spelling.nlx.NlxPackage#getBrackets()
 * @model
 * @generated
 */
public interface Brackets extends NoNElement
{
} // Brackets
