/**
 * generated by Xtext 2.33.0
 */
package org.xixum.modeler.spelling.nlx2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Line</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xixum.modeler.spelling.nlx.TableLine#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see org.xixum.modeler.spelling.nlx.NlxPackage#getTableLine()
 * @model
 * @generated
 */
public interface TableLine extends TableBorder
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute.
   * @see #setContent(String)
   * @see org.xixum.modeler.spelling.nlx.NlxPackage#getTableLine_Content()
   * @model
   * @generated
   */
  String getContent();

  /**
   * Sets the value of the '{@link org.xixum.modeler.spelling.nlx.TableLine#getContent <em>Content</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' attribute.
   * @see #getContent()
   * @generated
   */
  void setContent(String value);

} // TableLine
