# Required to make the "experiments" dir the default one for the output of the models
hydra:
  job:
    chdir: True
  run:
    dir: ./experiments/${model_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}

model_name: relik-reader-deberta-base-04062024-lrd08-1x4096-seed42  # -start-end-mask-0.001  # used to name the model in wandb and output dir
project_name: relik-reader # used to name the project in wandb
offline: false  # if true, wandb will not be used

defaults:
  - _self_
  - training: base
  - model: base
  - data: base
