/*
 * generated by Xtext 2.33.0
 */
package org.xixum.latex;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TexDslStandaloneSetup extends TexDslStandaloneSetupGenerated {

	public static void doSetup() {
		new TexDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
