/*
 * generated by Xtext 2.16.0
 */
package org.xixum.nlx.model.ui.contentassist

import org.xixum.nlx.model.ui.contentassist.AbstractNaturalLangProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class NaturalLangProposalProvider extends AbstractNaturalLangProposalProvider {
}
