/*
 * generated by Xtext 2.36.0
 */
package org.xixum.nlx.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractNaturalLangScopeProvider extends DelegatingScopeProvider {
}
